### ISSUE TITLE
Both checkboxes cannot be checked at the same time

### ISSUE THREAD

**Issue by N0mi99** [raise-isayan/BigIPDiscover#3]
![image](https://user-images.githubusercontent.com/34952213/196135775-e36958fd-0df5-467e-a3d8-02c8765c8201.png)
Hi,When I use burpsuite2022.9.2, I found that there is no error when installing this plugin, but the two checkboxes cannot be selected at the same time, and the checkbox on the right is gray and cannot be selected.
The JAVA version  is jdk-11.0.12.
Please take a look at this issue.

**Comment by raise-isayan** [comment]
The Community Edit settings are only available in Burp Community Edit and do not need to be used in the Professional Edition.
